### ISSUE TITLE
problems attempting to use a trained model to generate latex for a list of images

### ISSUE THREAD

**Issue by rkeiii** [untrix/im2latex#18]
Hello,

I have recently completed training your im2latex model using the steps provided. I now want to use the newly trained model to try to translate some textbook images of math equations into LaTeX. 

The main README says to do the following to run a trained model against a list of images:
```
Follow the notebook src/preprocessing/prepare_inferencing_dataset.ipynb to create a special dataset for this purpose and then the notebook src/tools/visualize.ipynb for extracting the predictions (from underlying h5py files).
```

However when I try to run through src/preprocessing/prepare_inferencing_dataset.ipynb I run into problems. Specifically the notebook always seems to complain that I am missing a dict_vocab.pkl file. When was this file supposed to be created in the process? Was I supposed to run through the preprocessing steps 0 -> 5 to prepare my raw math equation images for processing? The main README seems to say that I do not need to do this but the missing dict_vocab.pkl file error makes me think I do need to do this.

Thanks for any help you can provide.

**Comment by untrix** [comment]
Hi Ron,
    Sorry, some files were missing as we discussed. I've uploaded the missing files to the [download link](https://untrix.github.io/i2l/140k_download.html). Please download the file again and retry. Do let me know if you run into any other issues.

**Comment by rkeiii** [comment]
Thank you Sumeet. After downloading the new archive file I was able to resolve that particular issue. I have now made it to the point of actually running the model against 20 example images and get the following error.

My run command
```
(tensorflow_p27) ubuntu@ip-10-20-150-54:~/workspace/im2latex/src$ ./run.py -a 0.0001 -e -1 -b 1 -v -1 -i 2 --r-lambda 0.00005 --raw-data-folder /home/ubuntu/workspace/im2latex/data/dataset5/inferencing_20 --test --save-all-eval --restore "/home/ubuntu/workspace/im2latex/src/tb_metrics/2019-03-21 06-44-38 UTC STRIPS"

```

The following error
```
2019-04-02 09:31:22,300 - INFO - I2L/I2L_RNN/Output_Layer/yLogits_MLP/FC_2/fully_connected/biases:0 (358,) num_params = 358
2019-04-02 09:31:22,300 - INFO - I2L/I2L_RNN/Output_Layer/yLogits_MLP/Affine_3/fully_connected/weights:0 (358, 339) num_params = 121362
2019-04-02 09:31:22,301 - INFO - I2L/I2L_RNN/Output_Layer/yLogits_MLP/Affine_3/fully_connected/biases:0 (339,) num_params = 339
2019-04-02 09:31:22,301 - INFO - Total number of trainable params = 70984635
2019-04-02 09:31:22,301 - INFO - Vggnet: 0 (0.00%)
2019-04-02 09:31:22,301 - INFO - Convnet: 3909632 (5.51%)
2019-04-02 09:31:22,301 - INFO - Initializer: 7569300 (10.66%)
2019-04-02 09:31:22,301 - INFO - CALSTM_1: 57940330 (81.62%)
2019-04-02 09:31:22,301 - INFO - LSTM1_0: 21682500 (30.55%)
2019-04-02 09:31:22,301 - INFO - LSTM1_1: 18010500 (25.37%)
2019-04-02 09:31:22,301 - INFO - AttentionModel1: 18247330 (25.71%)
2019-04-02 09:31:22,301 - INFO - Output Layer: 1543677 (2.17%)
2019-04-02 09:31:22,301 - INFO - Embedding Matrix: 21696 (0.03%)
2019-04-02 09:31:22,427 - INFO - Flushing graph to disk
2019-04-02 09:31:23,450 - INFO - Created enqueue threads
2019-04-02 09:31:23,667 - INFO - Restoring session from checkpoint /home/ubuntu/workspace/im2latex/src/tb_metrics/2019-03-21 06-44-38 UTC STRIPS/snapshot-00014052
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1272: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1272: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-04-02 09:31:24,943 - INFO - Restored session from checkpoint /home/ubuntu/workspace/im2latex/src/tb_metrics/2019-03-21 06-44-38 UTC STRIPS/snapshot-00014052 at step 14052
2019-04-02 09:31:25,281 - INFO - Starting Testing Cycle
2019-04-02 09:31:25,281 - INFO - evaluation cycle starting at step 14052 for 5 steps
2019-04-02 09:31:26,810 - INFO - Done training -- epoch limit reached
2019-04-02 09:31:26,810 - INFO - Elapsed time for 14052 steps = 1.529375
Traceback (most recent call last):
  File "./run.py", line 268, in <module>
    main()
  File "./run.py", line 265, in main
    hyper.freeze()
  File "/home/ubuntu/workspace/im2latex/src/train_multi_gpu.py", line 523, in main
    coord.join(enqueue_threads)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1257, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: exceptions.ValueError: could not broadcast input array from shape (157,193,1) into shape (14,193,1)
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "commons/data_reader.py", line 443, in func
    d = self.next()

  File "commons/data_reader.py", line 395, in next
    for row in df_batch.itertuples(index=False)

  File "commons/data_reader.py", line 117, in get_array
    ar[h:h+height, w:w+width] = im_ar

ValueError: could not broadcast input array from shape (157,193,1) into shape (14,193,1)


	 [[{{node Testing/InputQueue/PyFunc}}]]
(tensorflow_p27) ubuntu@ip-10-20-150-54:~/workspace/im2latex/src$ 
```

**Comment by rkeiii** [comment]
I was able to confirm this seems to be a problem with my input data. When I run images from the same data set used to train the model through it everything goes according to plan. I have not yet determined though what exactly about my images is incompatible. I tried to make them as close to the training data as possible (PNG format, black text with transparent background).

**Comment by untrix** [comment]
Hi Ron, Glad to know that you've made progress. It is entirely possible that the inferencing scripts only work with training like images. I am sure it wouldn't accept images larger than the training set (126x1086). As mentioned earlier, I do intend to work on the inferencing scripts in the coming months which will make it super easy to run a trained model for prediction.

**Comment by Zhang-O** [comment]
@untrix , have you done the inferencing scripts to make it easy to run a trained model for prediction?

**Comment by untrix** [comment]
Hi @Zhang-O , I haven't made a lot of progress on that front unfortunately. What's your situation - DM me.

**Comment by untrix** [comment]
@Zhang-O Just follow the notebook src/preprocessing/prepare_inferencing_dataset.ipynb . But before that, make sure that all your images are no larger than 1086x126 pixels. You should be fine.

**Comment by untrix** [comment]
@Zhang-O Follow instructions in the notebook src/tools/predict.ipynb.
